default-messages:
  - " has died! RIP."
  - " died LMFAOO"
  - " killed them self"
  - " died in a hole"
  - " jumped"
  - " did a Epstein"

players:
  mikey:
    - " slipped on a banana"
    - " farted too hard"
    - " tripped over their ego"

